---
title: "ID Public Content"
author: "Roger Andre"
date: "2024-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Connect server info:
```{r, echo=FALSE}

# Access a Connect server and get info about published content

library(connectapi, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)

suppressWarnings( client <- connect() )
```


```{r get_content_info, echo=FALSE}
# get all content
all_content <- get_content(client, limit = Inf)
all_content <- 
  all_content %>% 
  select(guid, 
         name, 
         access_type, 
         created_time, 
         app_mode, 
         owner)

# Get the unique content types currently on the system
## rmd-static
## static
## quarto-static
## shiny
## python-shiny
## unknown
## jupyter-voila
## jupyter-static
## python-api
## python-fastapi
## python-dash
## api
## python-streamlit
## rmd-shiny
## quarto-shiny
## python-bokeh
## tensorflow-saved-model
```
### Current list of all published content types:
```{r get_all_types, echo=FALSE}

all_types <- unique(all_content$app_mode)

cat(unique(sort(all_types)), sep = "\n")
```

```{r get_info, echo=FALSE}
owner_list <- data.frame()

for (i in 1:nrow(all_content)) {
  owner_name <- all_content[i,]$owner[[1]]$username
  owner_guid <- all_content[i,]$owner[[1]]$guid
  owner_info <- list("owner_name" = owner_name, "owner_guid" = owner_guid)
  owner_list <- rbind(owner_list, owner_info)
}

all_content <- cbind(all_content, owner_list)
all_content <- all_content |> select(-owner)

public_content <- 
  filter(all_content, access_type == "all")
```

### Current list of "public" Interactive content

```{r get_public_interactive, echo=FALSE}
public_content |> 
  filter( !grepl("static", app_mode) ) |>
  select(name, owner_name, app_mode) |>
  print()
```

### Current list of "public" Static content
```{r get_public_static, echo=FALSE}
public_content |> 
  filter( grepl("static", app_mode) ) |>
  select(name, owner_name, app_mode) |>
  print()
```